export const baseLanguages = {
  cpp: { langName: "cpp", extension: ".cpp" },
  java: { langName: "java", extension: ".java" },
  python: { langName: "python", extension: ".py" },
  python3: { langName: "python", extension: ".py" },
  c: { langName: "c", extension: ".c" },
  csharp: { langName: "csharp", extension: ".cs" },
  javascript: { langName: "javascript", extension: ".js" },
  typescript: { langName: "typescript", extension: ".ts" },
  php: { langName: "php", extension: ".php" },
  swift: { langName: "swift", extension: ".swift" },
  kotlin: { langName: "kotlin", extension: ".kt" },
  dart: { langName: "dart", extension: ".dart" },
  golang: { langName: "golang", extension: ".go" },
  ruby: { langName: "ruby", extension: ".rb" },
  scala: { langName: "scala", extension: ".scala" },
  rust: { langName: "rust", extension: ".rs" },
  racket: { langName: "racket", extension: ".rkt" },
  erlang: { langName: "erlang", extension: ".erl" },
  elixir: { langName: "elixir", extension: ".ex" },
  mysql: { langName: "mysql", extension: ".sql" },
  postgresql: { langName: "postgresql", extension: ".sql" },
};

export const alternativeNames = {
  "c++": "cpp",
  "c#": "csharp",
  go: "golang",
  postgres: "postgresql",
};
